config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users 
  get 'welcome/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get 'welcome/website'
    get 'welcome/domain'
    get 'welcome/app'
    get 'welcome/StartSelling'
   resources :articles do
   resources :comments
end
resources :domains
resources :apps
resources :websites do
	 collection { post :search, to: 'websites#index' }
	end
  resources :amezons
end

app/models/amezon.rb
class Amezon < ApplicationRecord
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :comments
	has_many :avatars, as: :avatarable
end

app/models/avatar.rb
class Avatar < ApplicationRecord
	belongs_to :avatarable, polymorphic: true, optional: true
	mount_uploader :avatar, AvatarUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
   mount_uploader :avatar, AvatarUploader
   belongs_to :website, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
	 mount_uploader :avatar, AvatarUploader
	 has_many :images
   accepts_nested_attributes_for :images
end

app/controllers/amezons_controller.rb
class AmezonsController < ApplicationController
	def index
    @amezons = Amezon.all
  end
 
  def show
    @amezon = Amezon.find(params[:id])
  end
 
  def new
    @amezon = Amezon.new
  end
 
  def edit
    @amezon = Amezon.find(params[:id])
  end
 
  def create
    @amezon = Amezon.new(amezon_params)
 
    if @amezon.save
      redirect_to @amezon
    else
      render 'new'
    end
  end
 
  def update
    @amezon = Amezon.find(params[:id])
 
    if @amezon.update(article_params)
      redirect_to @amezon
    else
      render 'edit'
    end
  end
 
  def destroy
    @amezon = Amezon.find(params[:id])
    @amezon.destroy
 
    redirect_to amezons_path
  end
 
  private
    def amezon_params
      params.require(:amezon).permit(:name, :price)
    end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
    @apps = App.all
  end
 
  def show
    @app = App.find(params[:id])
  end
 
  def new
    @app = App.new
  end
 
  def edit
    @app = App.find(params[:id])
  end
 
  def create
    @app =App.new(app_params)
 
    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end
 
  def update
    @app = App.find(params[:id])
 
    if @app.update(app_params)
      redirect_to @app
    else
      render 'edit'
    end
  end
 
  def destroy
    @app = App.find(params[:id])
    @app.destroy
 
    redirect_to apps_path
  end
 
  private
    def app_params
      params.require(:app).permit(:name, :price, :days)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	 def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, :avatar)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:post_id, :avatar)
    end
end

app/helpers/amezons_helper.rb
module AmezonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:text) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<br><br><br>
<center><h1> EDIT ARTICLE</h1></center>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<br><br><br>
<div class= "container">
  <center>
  <%- model_class = Article -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  </center>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:image) %></th>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:title) %></th>
        <th><%= model_class.human_attribute_name(:text) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr> 
          <td><%= image_tag article.avatar.url %></td>
          <td><%= link_to article.id, article_path(article) %></td>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= article.created_at %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        article_path(article), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_article_path(article), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        article_path(article),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center>
  <%= link_to 'NEW ARTICLE',new_article_path, class: 'btn btn-primary' %>
  </center>
  <br>
  <br>
</div>

app/views/articles/new.html.erb
<br><br><br>
<center><h1> NEW ARTICLE</h1></center>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
 <br><br><br>
<div class= "container">
  <center>     
      <%- model_class = Article -%>
      <div class="page-header">
        <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
      </div>

      <dl class="dl-horizontal">
        <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
        <dd><%= @article.title %></dd>
        <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
        <dd><%= @article.text %></dd>
        <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
        <dd><%= image_tag @article.avatar.url %></dd>
      </dl>

      <%= link_to t('.back', :default => t("helpers.links.back")),
                    articles_path, :class => 'btn btn-default'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_article_path(@article), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  </center>
</div>
<br>