config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users 
  get 'welcome/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get 'welcome/website'
    get 'welcome/domain'
    get 'welcome/app'
    get 'welcome/StartSelling'
   resources :articles do
   resources :comments
end
resources :domains
resources :apps
resources :websites do
	 collection { post :search, to: 'websites#index' }
	end
  resources :amezons
end

app/models/amezon.rb
class Amezon < ApplicationRecord
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :comments
	has_many :avatars, as: :avatarable
end

app/models/avatar.rb
class Avatar < ApplicationRecord
	belongs_to :avatarable, polymorphic: true, optional: true
	mount_uploader :avatar, AvatarUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
   mount_uploader :avatar, AvatarUploader
   belongs_to :website, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
	 mount_uploader :avatar, AvatarUploader
	 has_many :images
   accepts_nested_attributes_for :images
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
    @apps = App.all
  end
 
  def show
    @app = App.find(params[:id])
  end
 
  def new
    @app = App.new
  end
 
  def edit
    @app = App.find(params[:id])
  end
 
  def create
    @app =App.new(app_params)
 
    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end
 
  def update
    @app = App.find(params[:id])
 
    if @app.update(app_params)
      redirect_to @app
    else
      render 'edit'
    end
  end
 
  def destroy
    @app = App.find(params[:id])
    @app.destroy
 
    redirect_to apps_path
  end
 
  private
    def app_params
      params.require(:app).permit(:name, :price, :days)
    end
end

app/helpers/amezons_helper.rb
module AmezonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/_form.html.erb
<br><br><br>
<div class= "container"> 

  <%= form_for @app, :html => { :class => "form-horizontal app" } do |f| %>

    <% if @app.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @app.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :days, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_field :days, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  apps_path, :class => 'btn btn-default' %>
      </div>
    </div>

  <% end %>
 
</div>

app/views/apps/edit.html.erb
<br><br><br>
<center><h1> EDIT APP</h1></center>
<%= render :partial => 'form' %>

app/views/apps/index.html.erb
<br><br><br>
<div class= "container">
  <center>
    <%- model_class = App -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
  </center>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:price) %></th>
      </tr>
    </thead>
    <tbody>
      <% @apps.each do |app| %>
        <tr> 
         <td><%= app.name %></td>
         <td><%= app.days %></td>
          <td><h5 class="text-right"> Price: <span style="color: green"><%= number_to_currency app.price %></span></h5></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        app_path(app), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_app_path(app), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        app_path(app),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center>
    <%= link_to 'NEW APP', new_app_path, class: 'btn btn-primary' %>
  </center>
</div>
<br>

app/views/apps/new.html.erb
<br><br><br>
<center><h1> NEW APP</h1></center>
<%= render :partial => 'form' %>

app/views/apps/show.html.erb
<br><br><br>
<div class= "container">
  <center>
    <%- model_class = App -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @app.name %></dd>
      <dd><%= @app.days %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %></strong></dt>
      <dd><%= @app.price %></dd>
    </dl>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                  apps_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_app_path(@app), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  app_path(@app),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </center>
</div>
<br>

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer>
  <div class="container">
    <div class="row">
      <div class="col l4 offset-l2 s12">
           <%= link_to "SELLING ON FLIPPA" %>
          <%= link_to "PRICING" %>
          <%= link_to "SUPPORT" %>
          <%= link_to "ABOUT US" %>
          <%= link_to "CARRIER" %>
          <%= link_to "BLOG" %>
      </div>
    </div>
  </div>
  <div class="container text-left">
    <p align="right">
      <a href="#" class="fa fa-facebook"></a>
      <a href="#" class="fa fa-twitter"></a>
      <a href="#" class="fa fa-google"></a>
      <a href="#" class="fa fa-linkedin"></a>
      <a href="#" class="fa fa-github"></a>
    </p>
  </div><!--End container-->
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <p align="right">
          COPYRIGHT © 2017 COMPANY.COM PTY LTD. ALL RIGHTS RESERVED.   
          TERMS  
          PRIVACY    
          SITE RULES   
        </p>
      </div>
    </div>
  </div>
</footer>
            

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'HOME', welcome_index_path %></li>
            <li>
              <%= link_to 'ARTICLE', articles_path, class: "dropbtn-a" %>
            </li>
              <li>
                <div class="dropdown">
                   <%= link_to 'WEBSITE', welcome_website_path, class: "dropbtn-a " %>
                  <div class="dropdown-content-1">
                    <div class="container">
                      <ul class="nav navbar-nav">
                        <li><a href="#">All</a></li>
                        <li><a href="#">Established Sites</a></li>
                        <li><a href="#">Starter Sites</a></li>
                        <li><a href="#">Editor's Choice</a></li>
                        <li><a href="#">Most Active</a></li>
                        <li><a href="#">Ending Soon</a></li>
                        <li><a href="#">Just Sold</a></li>
                        <li><a href="#">Shopify</a></li>
                        <li><a href="#">Valuation</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="dropdown">
                        <%= link_to 'DOMAIN', welcome_domain_path, class: "dropbtn-a dropbtn" %>
                  <div class="dropdown-content-2">
                    <div class="container">
                      <ul class="nav navbar-nav">
                        <li><a href="#">All</a></li>
                        <li><a href="#">Promoted</a></li>
                        <li><a href="#">Most Active</a></li>
                        <li><a href="#">Ending Soon</a></li>
                        <li><a href="#">Editor's Choice</a></li>
                        <li><a href="#">Just Sold</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="dropdown">
                    <%= link_to 'APP', welcome_app_path, class: "dropbtn-a dropbtn" %>
                  <div class="dropdown-content-3">
                    <div class="container">
                      <ul class="nav navbar-nav">
                        <li><a href="#">iOS</a></li>
                        <li><a href="#">Android</a></li>
                        <li><a href="#">Editor's Choice</a></li>
                        <li><a href="#">Most Active</a></li>
                        <li><a href="#">Ending Soon</a></li>
                        <li><a href="#">Just Sold</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                 <%= link_to 'AMEZON FBA', amezons_path, class: "dropbtn-a" %>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Log Out',  destroy_user_session_path,  method: :delete %></li>
              <li><a class="btn" data-toggle="modal" href="#myprofile" >Edit Profile</a>
                <!-- Modal -->
                <div class="modal fade" id="myprofile" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" >&times;</button>
                        <h4 class="modal-title">EDIT PROFILE FORM</h4>
                      </div>
                      <div class="modal-body">
                        <%= render 'users/registrations/edit' %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            <% else %>
              <li><a class="btn" data-toggle="modal" href="#myModal" >SIGN UP</a>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">SIGN UP FORM</h4>
                      </div>
                      <div class="modal-body">
                        <%= render 'users/registrations/new' %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li><a class="btn" data-toggle="modal" href="#mylogin" >LOG IN</a>
                  <!-- Modal -->
                <div class="modal fade" id="mylogin" role="dialog">
                  <div class="modal-dialog">
                      <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                         <h4 class="modal-title">LOG IN FORM</h4>
                      </div>
                      <div class="modal-body">
                        <%= render 'users/sessions/new' %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
            <li><div class= "btn btn-success"><%= link_to 'START SELLING', welcome_StartSelling_path %></li></div></li>
          </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
   </body>
</html>
    