config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users 
  get 'welcome/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get 'welcome/website'
    get 'welcome/domain'
    get 'welcome/app'
    get 'welcome/StartSelling'
   resources :articles do
   resources :comments
end
resources :domains
resources :apps
resources :websites do
	 collection { post :search, to: 'websites#index' }
	end
  resources :amezons
end

app/models/amezon.rb
class Amezon < ApplicationRecord
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :comments
	has_many :avatars, as: :avatarable
end

app/models/avatar.rb
class Avatar < ApplicationRecord
	belongs_to :avatarable, polymorphic: true, optional: true
	mount_uploader :avatar, AvatarUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
   mount_uploader :avatar, AvatarUploader
   belongs_to :website, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
	 mount_uploader :avatar, AvatarUploader
	 has_many :images
   accepts_nested_attributes_for :images
end

app/controllers/amezons_controller.rb
class AmezonsController < ApplicationController
	def index
    @amezons = Amezon.all
  end
 
  def show
    @amezon = Amezon.find(params[:id])
  end
 
  def new
    @amezon = Amezon.new
  end
 
  def edit
    @amezon = Amezon.find(params[:id])
  end
 
  def create
    @amezon = Amezon.new(amezon_params)
 
    if @amezon.save
      redirect_to @amezon
    else
      render 'new'
    end
  end
 
  def update
    @amezon = Amezon.find(params[:id])
 
    if @amezon.update(article_params)
      redirect_to @amezon
    else
      render 'edit'
    end
  end
 
  def destroy
    @amezon = Amezon.find(params[:id])
    @amezon.destroy
 
    redirect_to amezons_path
  end
 
  private
    def amezon_params
      params.require(:amezon).permit(:name, :price)
    end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
    @apps = App.all
  end
 
  def show
    @app = App.find(params[:id])
  end
 
  def new
    @app = App.new
  end
 
  def edit
    @app = App.find(params[:id])
  end
 
  def create
    @app =App.new(app_params)
 
    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end
 
  def update
    @app = App.find(params[:id])
 
    if @app.update(app_params)
      redirect_to @app
    else
      render 'edit'
    end
  end
 
  def destroy
    @app = App.find(params[:id])
    @app.destroy
 
    redirect_to apps_path
  end
 
  private
    def app_params
      params.require(:app).permit(:name, :price, :days)
    end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
  end
 
  def show
    @domain = Domain.find(params[:id])
  end
 
  def new
    @domain = Domain.new
  end
 
  def edit
    @domain = Domain.find(params[:id])
  end
 
  def create
    @domain = Domain.new(domain_params)
 
    if @domain.save
      redirect_to @domain
    else
      render 'new'
    end
  end
 
  def update
    @domain = Domain.find(params[:id])
 
    if @domain.update(domain_params)
      redirect_to @domain
    else
      render 'edit'
    end
  end
 
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy
 
    redirect_to domains_path
  end
 
  private
    def domain_params
      params.require(:domain).permit(:name, :price, :days)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:post_id, :avatar)
    end
end

app/helpers/amezons_helper.rb
module AmezonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/amezons/_form.html.erb
<br><br><br>
<div class= "container"> 

  <%= form_for @amezon, :html => { :class => "form-horizontal amezon" } do |f| %>

    <% if @amezon.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@amezon.errors.count, "error") %> prohibited this amezon from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @amezon.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_area :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:title) %>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
      <%=f.error_span(:price) %>
    </div>
    
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  amezons_path, :class => 'btn btn-default' %>
      </div>
    </div>

  <% end %>
 
</div>

app/views/amezons/edit.html.erb
<br><br><br>
<center><h1> EDIT AMEZON</h1></center>
<%= render :partial => 'form' %>

app/views/amezons/index.html.erb
<br><br><br>
<div class="container">
  <h4 style= "font-size:30px;"><b>Check out our Amazon FBA businesses for sale</b></h4>

  Amazon has created one of the most advanced fulfillment networks in the world, Fulfillment By Amazon. If you would like to sell your store, click here.
    <table class="table table-striped">
      <thead>
        <tr>
          <th> Amezon FBA</th>
          <th> price </th>
        </tr>
      </thead>
      <tbody>
        <% @amezons.each do |amezon| %>
          <tr> 
           <td><%= amezon.name %></td>
            <td><h5 class="text-right"> Price: <span style="color: green"><%= number_to_currency amezon.price %></span></h5></td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          amezon_path(amezon), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_amezon_path(amezon), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          amezon_path(amezon),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <center>
      <%= link_to 'NEW AMEZON', new_amezon_path, class: 'btn btn-primary' %>
    </center>
  <br>
</div>

app/views/amezons/new.html.erb
<br><br><br>
<center><h1> New Amezon</h1></center>
<%= render :partial => 'form' %>

app/views/amezons/show.html.erb
<br><br><br>
<div class= "container">
  <center>
    <%- model_class = Amezon -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @amezon.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %></strong></dt>
      <dd><%= @amezon.price %></dd>
    </dl>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                  amezons_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_amezon_path(@amezon), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  amezon_path(@amezon),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </center>
</div>
<br>

app/views/domains/_form.html.erb
<br><br><br>
<div class= "container">  
    <%= form_for @domain, :html => { :class => "form-horizontal domain" } do |f| %>

      <% if @domain.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
            <% @domain.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, :class => 'control-label col-lg-2' %>
        <div class="col-lg-4">
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
      </div>
       <div class="form-group">
      <%= f.label :days, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
        <%= f.text_field :days, :class => 'form-control' %>
      </div>
    </div>
      <div class="form-group">
        <%= f.label :price, :class => 'control-label col-lg-2' %>
        <div class="col-lg-4">
          <%= f.text_field :price, :class => 'form-control' %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    domains_path, :class => 'btn btn-default' %>
        </div>
      </div>

    <% end %>
  </div>
  <br>

app/views/domains/edit.html.erb
<br><br><br>
<center><h1> EDIT DOMAIN</h1></center>
<%= render :partial => 'form' %>

app/views/domains/index.html.erb
<br><br><br>
<div class= "container">
  <center>
    <%- model_class = Domain -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
  </center>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:price) %></th>
      </tr>
    </thead>
    <tbody>
      <% @domains.each do |domain| %>
        <tr> 
         
          <td><%= domain.name %></td>
          <td><%= domain.days %></td>
          <td><h5 class="text-right"> Price: <span style="color: green"><%= number_to_currency domain.price %></span></h5></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        domain_path(domain), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_domain_path(domain), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        domain_path(domain),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center>
      <%= link_to 'NEW DOMAIN', new_domain_path, class: 'btn btn-primary' %>
  </center>
</div>
<br>

app/views/domains/new.html.erb
<br><br><br>
<center><h1> NEW DOMAIN</h1></center>
<%= render :partial => 'form' %>

app/views/domains/show.html.erb
<br><br><br>
<div class= "container">
  <center> 
  <%- model_class = Domain -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @domain.name %></dd>
    <dd><%= @domain.days %></dd>
    <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
    <dd> <%= @domain.price %></dd>
  </dl>

  <%= link_to t('.back', :default => t("helpers.links.back")),
                domains_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_domain_path(@domain), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                domain_path(@domain),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  </center>
</div>
<br>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :image_post_id %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar, id: :image_avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.post_id %></td>
        <td><%= image.avatar %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @image.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @image.avatar %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>